tutorial-dyn2b:
	@cp ../models/templates/CMakeLists.txt ../gen/CMakeLists.txt
	@stst -s "<>" -t ../models/templates/applications tutorial_dyn2b.application ../gen/solver.gen-ir.json > ../gen/main.c

tutorial-dyn2b-slv-print:
	@cp ../models/templates/CMakeLists.txt ../gen/CMakeLists.txt
	@stst -s "<>" -t ../models/templates/applications tutorial_dyn2b_slv_print.application ../gen/solver.gen-ir.json > ../gen/main.c

tutorial-dyn2b-slv-robif2b:
	@cp ../models/templates/CMakeLists.txt ../gen/CMakeLists.txt
	@stst -s "<>" -t ../models/templates/applications tutorial_dyn2b_slv_robif2b.application ../gen/solver.gen-ir.json > ../gen/main.c

tutorial-dyn2b-slv-print-ctrl:
	@cp ../models/templates/CMakeLists.txt ../gen/CMakeLists.txt
	@stst -s "<>" -t ../models/templates/applications tutorial_dyn2b_slv_print_ctrl.application ../gen/solver.gen-ir.json > ../gen/main.c

tutorial-dyn2b-slv-robif2b-ctrl:
	@cp ../models/templates/CMakeLists.txt ../gen/CMakeLists.txt
	@stst -s "<>" -t ../models/templates/applications tutorial_dyn2b_slv_robif2b_ctrl.application ../gen/solver.gen-ir.json > ../gen/main.c